[package]
name = "php-tokio"
repository = "https://github.com/danog/php-tokio"
homepage = "https://github.com/danog/php-tokio"
license = "AGPL-3.0-or-later"
description = "Use any async Rust library from PHP!"
version = "0.1.0"
authors = ["Daniil Gentili <daniil@daniil.it>"]
edition = "2021"

[dependencies]
nicelocal-ext-php-rs = "0.10.3"
tokio = { version = "1", features = ["full"] }
tokio-pipe = "*"
lazy_static = "1.4.0"
libc = "*"
php-tokio-derive = { version = "=0.1.0", path = "./crates/macros" }


[workspace]
members = [
    "crates/macros",
]
